export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const SELLER_SIGNIN_REQUEST = 'SELLER_SIGNIN_REQUEST';
export const SELLER_SIGNIN_SUCCESS = 'SELLER_SIGNIN_SUCCESS';
export const SELLER_SIGNIN_FAIL = 'SELLER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const SELLER_REGISTER_REQUEST = 'SELLER_REGISTER_REQUEST';
export const SELLER_REGISTER_SUCCESS = 'SELLER_REGISTER_SUCCESS';
export const SELLER_REGISTER_FAIL = 'SELLER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';